const fs = require('fs');
const nodemailer = require('nodemailer');

// 配置
const HISTORY_FILE = 'history.json';
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASS;
const RECIPIENT_EMAIL = process.env.RECIPIENT_EMAIL;

// 辅助函数
function getRegion(source) {
    const cnSources = ['36Kr', '财联社', '掘金', '量子位', 'QbitAI'];
    const usSources = ['TechCrunch', 'ProductHunt', 'GitHub', 'HackerNews', 'HuggingFace', '基建', '汽车'];
    if (cnSources.some(s => source.includes(s))) return '🇨🇳';
    if (usSources.some(s => source.includes(s))) return '🇺🇸';
    return '🌐';
}

function loadHistory() {
    try {
        if (fs.existsSync(HISTORY_FILE)) {
            return JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'));
        }
    } catch (e) { console.error('History load error:', e); }
    return [];
}

async function main() {
    console.log('🚀 Daily Digest Bot - Preparing Report...\n');
    const history = loadHistory();

    // 筛选过去 24 小时内的高分内容 (Score >= 5)
    const oneDayAgo = Date.now() - (24 * 60 * 60 * 1000);
    const dailyItems = history.filter(h => h.time >= oneDayAgo && (h.score || 0) >= 5);

    // 去重 (以防 history 有重复)
    const uniqueItems = [];
    const seen = new Set();
    dailyItems.forEach(item => {
        if (!seen.has(item.url)) {
            seen.add(item.url);
            uniqueItems.push(item);
        }
    });

    // 排序
    uniqueItems.sort((a, b) => b.score - a.score);

    if (uniqueItems.length === 0) {
        console.log('❌ No high-score items today. Skipping digest.');
        return;
    }

    console.log(`📊 Digest Items: ${uniqueItems.length}`);

    // 分类
    const groups = {
        '🚨 Millionaire Signals (Score >= 10)': uniqueItems.filter(i => i.score >= 10),
        '🛠️ Product & Tools': uniqueItems.filter(i => i.score < 10 && (i.source.includes('ProductHunt') || i.source.includes('GitHub') || i.source.includes('HuggingFace'))),
        '📰 Industry News': uniqueItems.filter(i => i.score < 10 && !i.source.includes('ProductHunt') && !i.source.includes('GitHub') && !i.source.includes('HuggingFace'))
    };

    let htmlContent = '';

    for (const [name, items] of Object.entries(groups)) {
        if (items.length === 0) continue;

        htmlContent += `<div style="margin-bottom:30px;">
      <h2 style="color:#333;border-bottom:2px solid #333;padding-bottom:10px;margin-bottom:15px;">${name}</h2>
      <ul style="padding-left:0;list-style:none;">`;

        items.forEach(item => {
            const region = item.region || getRegion(item.source);
            const summaryHtml = item.summary ? `<div style="font-size:14px;color:#555;margin:4px 0 8px 0;line-height:1.5;">${item.summary}</div>` : '';

            htmlContent += `<li style="margin-bottom:20px; border-bottom:1px solid #eee; padding-bottom:15px;">
        <div style="font-size:18px;font-weight:bold;margin-bottom:5px;">
          <a href="${item.url}" style="text-decoration:none;color:#000;">${item.title}</a>
          <span style="background:#eee;color:#333;font-size:12px;padding:2px 6px;border-radius:4px;margin-left:8px;">${item.score}</span>
        </div>
        ${summaryHtml}
        <div style="font-size:12px;color:#888;">${region} ${item.source} • ${new Date(item.time).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</div>
      </li>`;
        });
        htmlContent += '</ul></div>';
    }

    // 发送
    if (!EMAIL_USER || !EMAIL_PASS) {
        console.log('⚠️ No credentials');
        return;
    }

    let transporter = nodemailer.createTransport({
        service: 'qq', secure: true,
        auth: { user: EMAIL_USER, pass: EMAIL_PASS },
        tls: { rejectUnauthorized: false }
    });

    const dateStr = new Date().toLocaleDateString('zh-CN');

    await transporter.sendMail({
        from: `"Daily Insight Digest" <${EMAIL_USER}>`,
        to: RECIPIENT_EMAIL,
        subject: `📚 Daily Insight Digest - ${dateStr}`,
        html: `<div style="font-family:Georgia, serif; max-width:800px; margin:0 auto; color:#333; line-height:1.6;">
        <div style="text-align:center;margin-bottom:40px;padding-top:20px;">
          <h1 style="font-size:32px;margin-bottom:10px;">DAILY INSIGHT DIGEST</h1>
          <p style="color:#666;font-style:italic;">${dateStr} • ${uniqueItems.length} Stories</p>
        </div>
        ${htmlContent}
        <div style="margin-top:50px;text-align:center;font-size:12px;color:#999;border-top:1px solid #eee;padding-top:20px;">
          Generated by Bot v4.0
        </div>
      </div>`
    });
    console.log('✅ Digest sent!');
}

main();
